version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "fix(deps)"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directories:
    - "/admin-ui/"
    - "/booking-ui/"
    - "/commons/ts/"
    - "/e2e/"
  schedule:
    interval: daily
  commit-message:
    prefix: "fix(deps)"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "fix(deps)"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "build"
    include: "scope"