name: Build Admin UI (dev)

on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set version env
      run: echo "CI_VERSION=$(cat version.txt | awk NF)" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Log into ghcr.io registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: push
      uses: docker/build-push-action@v5
      with:
        build-args: CI_VERSION=${{ env.CI_VERSION }}-dev
        context: ./
        file: Dockerfile.admin-ui
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.REGISTRY }}/seatsurfing/admin-ui:dev
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
